# Generated by Django 5.0.3 on 2024-03-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member2',
            fields=[
                ('firstname', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=255)),
                ('tahun', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
