# Generated by Django 5.0.3 on 2024-03-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_member2_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member3',
            fields=[
                ('namapertama', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('namabelakang', models.CharField(max_length=255)),
                ('periode', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
