# Generated by Django 5.0.3 on 2024-04-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_member3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('password', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
